import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Outfit, Roboto } from "next/font/google";
import { CartProvider } from "@/context/CartContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/AuthContext";
import { getSession } from "@/services/authService";
import { getPlatformSettings } from "@/services/superAdminService";
import { headers } from "next/headers";
import ThemeProvider from "@/components/ThemeProvider";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const url = headersList.get('x-url') || '';
  
  let role: string | undefined = undefined;
  if (url.includes('/admin')) role = 'admin';
  else if (url.includes('/superadmin')) role = 'superadmin';
  else if (url.includes('/waiter')) role = 'waiter';
  
  const [session, settings] = await Promise.all([
    getSession(role),
    getPlatformSettings()
  ]);

  const fontMap: Record<string, string> = {
    "Geist Sans": "var(--font-geist-sans)",
    "Inter": "var(--font-inter)",
    "Outfit": "var(--font-outfit)",
    "Roboto": "var(--font-roboto)",
  };

  const selectedFont = fontMap[settings.fontFamily] || "var(--font-geist-sans)";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${outfit.variable} ${roboto.variable} antialiased`}
      >
        <ThemeProvider primaryColor={settings.primaryColor} fontFamily={settings.fontFamily} />
        <AuthProvider initialSession={session} role={role}>
          <CartProvider>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
